ios/Podfile.lock, ios/screens/MapViewController/BaseMapViewController.h, ios/screens/MapViewController/BaseMapViewController.m, ios/screens/MapViewController/FullMapViewController.m, ios/screens/MapViewController/ItemDetailsMapViewController/ItemDetailsMapViewController.m, ios/screens/MapViewController/MapViewState/MapViewState.h, ios/screens/MapViewController/MapViewState/MapViewState.m
Reverts radzima-green-travel/green-travel-combine#108
=> Revert "[107]fix:location view on details map is not of the same size as on f…"

src/components/molecules/AppMapBottomSearchMenu/AppMapBottomSearchMenu.tsx, src/components/molecules/SearchListItem/styles.ts, src/components/screens/AppMap/AppMap.tsx
Search-history deletion for map-screen was implemented.
=> [RN] add: search-history deletion for map-screen

ios/Podfile.lock, package.json, src/core/store.ts, src/storage/Storage.ts, yarn.lock
=> RN-300: add MMKV-library

src/components/screens/ObjectDetailsMap/ObjectDetailsMap.tsx
Spinner was working all time regadless of data was loaded or not.
=> [RN-300]: fix spinner at the button on ObjectDetailMap screen

src/core/store.ts
Ticket: https://github.com/radzima-green-travel/green-travel-combine/issues/264
=> [RN-264]: migrate-to-MMKV-for-iOS

src/components/molecules/ObjectDescriptionSource/ObjectDescriptionSource.tsx, src/locale/en.json, src/locale/ru.json, src/locale/zh.json
Requirements of this ticket were updated: https://github.com/radzima-green-travel/green-travel-combine/issues/253
=> [RN]: refactor source field at ObjectDescription according new design

ios/greenTravel/Images.xcassets/Colors/areaFill.colorset/Contents.json, ios/greenTravel/Images.xcassets/Colors/areaOutline.colorset/Contents.json, ios/screens/MapViewController/ItemDetailsMapViewController/ItemDetailsMapViewController.m, ios/utilities/Colors.h, ios/utilities/Colors.m, ios/utilities/StyleUtils.m
Change polygon fill color to green, border style from dash to line and color to green.
=> fix/402 Change polygon and border colors

ios/screens/SearchViewController/SearchViewController.m
Added UITapGestureRecognizer, scrollViewWillBeginDragging methods
[https://github.com/radzima-green-travel/green-travel-combine/issues/413](url)
=> fix/413 dismiss keyboard when scrolling search results and touching outside of SearchBar

.github/workflows/codeql-analysis.yml
=> feat(456): add codeql scanner

package.json, yarn.lock
Reverts radzima-green-travel/green-travel-combine#522
=> Revert "build(deps): bump react-native-fast-image from 8.3.7 to 8.5.11"

ios/Podfile, ios/Podfile.lock, ios/greenTravel.xcodeproj/project.pbxproj, ios/greenTravel/Info.plist
Fixes popup that asks for location in RN.
#562 
=> fix(562): no location service in RN

src/assets/colors.ts, src/components/screens/ObjectDetailsMap/ObjectDetailsMap.tsx, src/components/screens/ObjectDetailsMap/styles.ts
Route line view was change according design.
300
=> fix(300): change route line color

src/navigation/screenOptions/useScreenOptions.tsx
Change top-bar background according design in figma, gradient was replaced with apple-color (EPMEDUGRN-297);
=> fix(297): change header background

declarations.d.ts, src/components/atoms/Card/Card.tsx, src/components/atoms/Card/styles.ts, src/components/atoms/ImageSlider/ImageSlider.tsx, src/components/screens/ObjectDetails/ObjectDetails.tsx, src/core/sagas/authentification/authentification.ts, src/core/sagas/bootstrap/bootstrap.ts, src/core/selectors/app.ts, src/core/selectors/index.ts, src/navigation/navigators/TabNavigator.tsx
Add default photo if there is no picture or picture is not downloaded from the server (EPMEDUGRN-52);
=> fix(52): add default photo

ios/screens/MainViewController/MainViewController.m
Disables sign up for production (including TestFlight) builds.
#577 
=> fix(577): disable sign up feature for production builds

ios/screens/ProfileRootViewController/CodeConfirmationController/CodeConfirmationViewController.m, ios/screens/ProfileRootViewController/ResetPasswordNewPasswordViewController/ResetPasswordNewPasswordViewController.m, ios/screens/ProfileRootViewController/ResetPasswordPassCodeViewController/ResetPasswordPassCodeViewController.m
1. Clear new password field after submit.
2. Clear pass code field after submit.
#478 
=> fix(478): clear new password, pass code fields after submit

ios/greenTravel.xcodeproj/project.pbxproj, ios/screens/MainViewController/MainViewController.m, ios/utilities/AccessibilityIdentifiers.h, ios/utilities/AccessibilityIdentifiers.m, ios/utilities/AccessibilityUtils.h, ios/utilities/AccessibilityUtils.m
Adds accessibility ids for tab bar.
#590 
=> feat(590): add accessibility ids

ios/models/ProfileCellModel/SettingsTableViewCellModel.h, ios/models/ProfileCellModel/SettingsTableViewCellModel.m, ios/screens/ProfileRootViewController/CodeConfirmationController/CodeConfirmationViewController.m, ios/screens/ProfileRootViewController/LoginViewController/BaseFormViewController.m, ios/screens/ProfileRootViewController/LoginViewController/LoginViewController.m, ios/screens/ProfileRootViewController/ProfileTableViewController/ProfileTableViewCell/ProfileTableViewCell.h, ios/screens/ProfileRootViewController/ProfileTableViewController/ProfileTableViewCell/ProfileTableViewCell.m, ios/screens/ProfileRootViewController/ProfileTableViewController/ProfileTableViewController.m, ios/screens/ProfileRootViewController/ProfileTableViewController/ProfileTableViewControllerUtils.m, ios/screens/ProfileRootViewController/ResetPasswordNewPasswordViewController/ResetPasswordNewPasswordViewController.m
Puts login flow into modal.
#603 
=> feat(603): present controller in modal

ios/controllers/UserController/UserController.h, ios/controllers/UserController/UserController.m, ios/screens/ProfileRootViewController/LoginViewController/BaseFormViewController.m, ios/screens/ProfileRootViewController/LoginViewController/LoginViewController.m, ios/screens/ProfileRootViewController/ProfileTableViewController/ProfileTableViewController.m
Removes unnecessary states from being processed in ProfileTableViewController. Fixes #605.
#605 
=> fix(605): do not listen for unnecessary states

src/components/atoms/FormInput/FormInput.tsx, src/components/atoms/FormInput/styles.ts, src/components/molecules/GeneralListItem/styles.ts, src/components/organisms/AuthForm/styles.ts, src/navigation/navigators/ProfileNavigator.tsx, src/screens/Profile/Profile.tsx
Add dark theme to profile screen
=> feat(udated): profile screen dark theme

src/locale/en.json, src/locale/ru.json, src/locale/zh.json, src/navigation/navigators/AppMapNavigatior.tsx, src/navigation/navigators/AuthNavigator.tsx, src/screens/CheckEmail/CheckEmail.tsx, src/screens/CheckEmail/hooks/useCheckEmail.tsx, src/screens/Profile/Profile.tsx, src/screens/ProfileDetails/ProfileDetails.tsx, src/screens/RestorePassword/RestorePassword.tsx, src/screens/SignInPassword/SignInPassword.tsx, src/screens/SignInPassword/hooks/useSignInPassword.tsx, src/screens/SignUpForm/SignUpForm.tsx, src/screens/SignUpForm/hooks/useSignUpForm.tsx, src/screens/Splash/Splash.tsx
=> feat(text): text translate

src/components/atoms/BookmarkItem/BookmarkItem.tsx, src/components/atoms/Button/Button.tsx, src/components/atoms/HeaderSearchbar/HeaderSearchbar.tsx, src/components/atoms/HeaderTitle/HeaderTitle.tsx, src/components/atoms/HeaderTitle/index.ts, src/components/atoms/HeaderTitle/styles.ts, src/components/atoms/Icon/Icon.tsx, src/components/atoms/index.ts, src/components/molecules/AnimatedBackCircleButton/AnimatedBackCircleButton.tsx, src/components/molecules/AnimatedHeaderBookmarkButton/AnimatedHeaderBookmarkButton.tsx, src/components/molecules/DetailsPageCapture/DetailsPageCapture.tsx, src/components/molecules/ObjectDescription/ObjectDescription.tsx, src/components/molecules/ObjectDescriptionSource/ObjectDescriptionSource.tsx, src/components/molecules/ObjectInlcudesItem/ObjectInlcudesItem.tsx, src/components/molecules/SearchListItem/SearchListItem.tsx, src/components/organisms/HomeSectionBar/HomeSectionBar.tsx, src/components/organisms/ObjectIncludes/ObjectIncludes.tsx, src/components/organisms/SearchList/SearchList.tsx, src/core/helpers/common.ts, src/core/types/common.ts, src/navigation/navigators/TabNavigator.tsx, src/navigation/screenOptions/useScreenOptions.tsx, src/screens/Bookmarks/Bookmarks.tsx, src/screens/Home/Home.tsx, src/screens/Home/screenOptions.tsx, src/screens/ObjectDetails/ObjectDetails.tsx
1. TestIDs were added.
2. Wrapper (View) was added for some components to ensure that testID will be applied.
https://github.com/radzima-green-travel/green-travel-combine/issues/590
=> Add testIds

ios/screens/RootViewController/RootViewController.m
Adds `DEFAULT_FRAMEWORK` option to `.env` file.
**Warning** - as a developer, please add `DEFAULT_FRAMEWORK` to your `.env` and execute `yarn rnuc .env` on project root, then rebuild.
#657 
=> feat(657): add DEFAULT_FRAMEWORK option

src/core/constants.ts, src/locale/en.json, src/locale/ru.json, src/locale/zh.json, src/screens/AuthMethodSelection/AuthMethodSelection.tsx, src/screens/AuthMethodSelection/styles.ts
1. Added Terms of Usage and Privacy Policy links and text.
2. Updated translations for en and zh.
[Add social networks buttons](https://github.com/radzima-green-travel/green-travel-combine/pull/662)
=> Update AuthMethodSelection screen

.gitignore, ios/.gitignore, ios/.xcode.env.local
- update gitignore
- remove hardcoded path to homebrew node
=> fix(env): remove xcode env local

src/core/sagas/authentification/signInSaga.ts, src/core/sagas/authentification/signUpSaga.ts, src/core/sagas/authentification/updateUserAttributesSaga.ts, src/core/sagas/settings/changeAppLanguage.ts
Added locale to signUp and forgotPasswordSubmit
https://github.com/radzima-green-travel/green-travel-combine/pull/654
=> [EPMEDUGRN-244] add locale to signUp and forgotPasswordSubmit

src/components/atoms/SnackBar/styles.ts, src/components/molecules/GeneralListItem/GeneralListItem.tsx, src/components/molecules/GeneralListItem/styles.ts, src/core/helpers/common.ts, src/screens/Profile/Profile.tsx, src/screens/Profile/hooks/useProfile.tsx, src/screens/Profile/styles.ts
fixed GeneralListItem and SnackBar styles
[224](https://jira.epam.com/jira/browse/EPMEDUGRN-224)
=> fix(fixed): [244] GeneralListItem and SnackBar style

src/screens/EmailValidation/EmailValidation.tsx, src/screens/EmailValidation/hooks/useEmailValidation.tsx
Add loading spinner  on resend button
[486](https://jira.epam.com/jira/browse/EPMEDUGRN-486)
=> fix(fixed): [486] fix resend button loading

src/screens/EmailValidation/hooks/useEmailValidation.tsx
Fix navigation for new password screen
[492](https://jira.epam.com/jira/browse/EPMEDUGRN-492)
=> fix(fixed): [492] replace new password screen

src/components/containers/FavoriteButtonContainer/FavoriteButtonContainer.tsx, src/components/molecules/AnimatedHeaderBookmarkButton/AnimatedHeaderBookmarkButton.tsx
Fixed test id for header bookmark button.
[508](https://jira.epam.com/jira/browse/EPMEDUGRN-508)
[Previous PR](https://github.com/radzima-green-travel/green-travel-combine/pull/712)
=> fix(508): fix visibility of header bookmark button test id

src/assets/colors.ts, src/core/helpers/getAppVersion.ts, src/core/helpers/index.ts, src/locale/en.json, src/locale/ru.json, src/locale/zh.json, src/navigation/hooks/useAndroidNavbarStyle.ts, src/screens/Profile/Profile.tsx, src/screens/Profile/styles.ts
1. Display app version (for dev only - app version and build number);
2. Updated useAndroidNavbarStyle to remove warning.
[526](https://jira.epam.com/jira/browse/EPMEDUGRN-526)
=> feat(526): display app version

src/navigation/navigators/RootNavigator.tsx
Fix double bottomSheet for OptionalUpdateScreen
=> [509] fix double bottomSheet

src/components/atoms/Card/Card.tsx, src/components/molecules/CategoryCard/CategoryCard.tsx, src/components/organisms/HomeSectionBar/HomeSectionBar.tsx, src/core/helpers/common.ts, src/core/types/common.ts, src/screens/BookmarksList/BookmarksList.tsx, src/screens/CategoriesList/CategoriesList.tsx
fix testID for object
[552](https://jira.epam.com/jira/browse/EPMEDUGRN-552)
=> [552] fix testID for object

src/assets/colors.ts, src/components/atoms/SnackBar/SnackBar.tsx, src/components/atoms/SnackBar/styles.ts, src/screens/ObjectDetails/hooks/useObjectDetails.tsx, src/screens/Profile/hooks/useProfile.tsx, src/screens/ProfileDetails/hooks/useProfileDetails.tsx
Update SnackBar component according new design
=> fix(changed): snackBar design

src/components/atoms/ClusterMap/ClusterMap.tsx, src/components/atoms/ClusterMap/types.ts, src/screens/AppMap/AppMap.tsx, src/screens/AppMap/hooks/useAppMap.tsx, src/screens/ObjectDetailsMap/ObjectDetailsMap.tsx, src/screens/ObjectDetailsMap/hooks/useObjectDetailsMap.tsx
Add locale for MapView to provide correct translations
<details>
</details>
[111](https://jira.epam.com/jira/browse/EPMEDUGRN-111)
=> fix(fixed): [EPMEDUGRN-111] fix locale for MapView

package.json, patches/react-native+0.72.6.patch, yarn.lock
=> fix(fixed): add patch for RN 0.72.6

package.json, src/components/organisms/ObjectDetailsReportInaccuraciesMenu/ObjectDetailsReportInaccuraciesMenu.tsx, src/core/hooks/useBottomMenu.ts, src/screens/ObjectDetailsShareExperience/hooks/useShareExperienceMenu.ts
Handles Android hardware button presses for back navigation to dismiss bottom menus
[656](https://jira.epam.com/jira/browse/EPMEDUGRN-656)
=> fix(656): handle back press for open bottom menus

src/components/molecules/ObjectAddInfoMenu/ObjectAddInfoMenu.tsx, src/components/molecules/ObjectAddInfoMenu/components/Input/Input.tsx, src/components/molecules/ObjectDescription/ObjectDescription.tsx, src/components/organisms/ObjectDetailsAddInfoMenu/ObjectDetailsAddInfoMenu.tsx, src/screens/ObjectDetailsAddInfo/ObjectDetailsAddInfo.tsx
1) Fix Backgdrop Animation for menus
2) Make auto focus faster
3) Fix description styles
=> improve UX for add info menu, fix style for description

src/core/helpers/common.ts, src/core/selectors/search.ts
Handles punctuation by sanitizing inputs, refactors search selectors, fixes type inference
[EPMEDUGRN-706](https://jira.epam.com/jira/browse/EPMEDUGRN-706)
=> fix(706): search by address

src/locale/ru.json
Update Russian text on Object screen: Показать меньше instead of Скрыть
<details>
</details>
<details>
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-737
NA
NA
=> fix(737): change text on object screen

src/components/molecules/ObjectShareExperienceMenu/ObjectShareExperienceMenu.tsx, src/locale/ru.json, src/screens/ObjectDetailsShareExperience/ObjectDetailsShareExperience.tsx, src/screens/ObjectDetailsShareExperience/hooks/useObjectShareExperienceAnalytics.ts, src/screens/ObjectDetailsShareExperience/hooks/useShareExperienceData.ts, src/screens/ObjectDetailsShareExperience/hooks/useShareExperienceMenu.ts
Fix issue related with the system resets the user-specified time
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/7524cb00-b3e0-43f5-bd67-57b43812236c
</details>
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/9bb00650-b459-4040-bac7-32217199156f
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-754
NA
NA
=> fix(754): the system resets the user-specified time

src/assets/colors.ts, src/components/atoms/Chip/Chip.tsx, src/components/atoms/Chip/constants.ts, src/components/atoms/Chip/index.ts, src/components/atoms/Chip/styles.ts, src/components/atoms/index.ts
Add chip component 
https://www.figma.com/design/7jtoTkhlIvDaMvC6z5YmDe/TravelApp-Design-System?node-id=2141-3488&t=EwWbduw6fmpIwn4q-0
NA
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/aeada730-481f-4f05-859d-375009751e75
</details>
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/4de20a52-0e80-4f66-8d9e-65b7a89702d7
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-766
NA
NA
=> feat(766): add chip

src/components/atoms/Checkbox/Checkbox.tsx, src/components/atoms/Checkbox/constants.ts, src/components/atoms/Checkbox/index.ts, src/components/atoms/Checkbox/styles.ts, src/components/atoms/index.ts
Add checkbox component
https://www.figma.com/design/aD00e3k2pLwhEhBDq5VkJO/Mobile-Application?node-id=13773-30457&t=NhX8Cepqcqoq9Cg2-0
NA
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/c8da6364-3509-4a9f-a550-ccfe5d7abcb2
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-766
NA
NA
=> feat(766): add checkbox

src/components/atoms/Multiswitch/Multiswitch.tsx, src/components/atoms/Multiswitch/constants.ts, src/components/atoms/Multiswitch/index.ts, src/components/atoms/Multiswitch/styles.ts, src/components/atoms/index.ts
Add multiswitch component
https://www.figma.com/design/7jtoTkhlIvDaMvC6z5YmDe/TravelApp-Design-System?node-id=3323-2426&t=IkJMJ1OSBkz50oNc-0
NA
<details>
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-766
NA
NA
=> feat(766): add multiswitch

migrateToExpoList.ts, package.json, src/services/AnalyticsService.ts, yarn.lock
1. Changed analytics package from @amplitude/react-native to @amplitude/analytics-react-native;
2. Fixed code in AnalyticsService to match the previous implementation.
=> fix(expo): fix amplitude

.easignore, .gitignore, app.config.ts, app.json, eas.json
=> Tech task/expo build ci

src/core/hooks/useTimeRange.ts, src/core/sagas/visitedObjects/scheduleShareExperienceMenuSaga.ts, src/screens/ObjectDetailsMap/hooks/useObjectDetailsMap.tsx, src/services/HapticFeedbackService.ts
Fixed haptic feedback - used selectionAsync and notificationAsync methods to have the same behavior as in the previous implementation.
=> fix(000): fix haptic feedback

src/core/helpers/common.ts
=> fix(fixed): add check for get analyticsMetadata property

src/components/atoms/Card/Card.tsx, src/components/atoms/HeaderTitle/HeaderTitle.tsx
Update attributes to category elements for automation testing
NA
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/c304b91c-98ae-4cfd-bc6c-1537c853ea19
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-747
NA
NA
=> feat(747): update accessibilityLabels

src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/appMap.ts, src/api/graphql/queries/common.ts, src/api/graphql/queries/homePage.ts, src/api/graphql/queries/index.ts, src/components/atoms/ClusterMap/ClusterMap.tsx, src/components/molecules/AppMapBottomMenu/AppMapBottomMenu.tsx, src/core/actions/appMap.ts, src/core/actions/index.ts, src/core/helpers/common.ts, src/core/hooks/useFindZoomForObjectInCluster.ts, src/core/reducers/appMap.ts, src/core/reducers/index.ts, src/core/rootSaga.ts, src/core/sagas/appMap/appMap.ts, src/core/sagas/appMap/getAppMapObjectsSaga.ts, src/core/sagas/appMap/index.ts, src/core/sagas/homePage/getHomePageDataSaga.ts, src/core/sagas/index.ts, src/core/selectors/appMap.ts, src/core/selectors/mapSelectors.ts, src/core/store.ts, src/core/transformators/appMap.ts, src/core/transformators/common.ts, src/core/types/api/graphql.ts, src/core/types/common.ts, src/screens/AppMap/AppMap.tsx, src/screens/AppMap/hooks/useAppMap.tsx
1) Add query and logic to fetch app map data
2) Remove legacy logic
https://jira.epam.com/jira/browse/EPMEDUGRN-803
=> feat(updated): [EPMEDUGRN-803] migrate home page to graph ql approach

src/components/atoms/Multiswitch/Multiswitch.tsx, src/core/sagas/app/getAppConfigurationSaga.ts, src/core/sagas/bootstrap/bootstrap.ts, src/screens/Filters/hooks/useFilters.tsx
=> feat(775): fix reqions request

src/api/graphql/GraphQLAPI.ts, src/core/actions/filters.ts, src/core/reducers/filters.ts, src/core/sagas/filters/getInitialFiltersSaga.ts, src/core/selectors/filtersPage.ts
=> feat(775): add getFilterObjects for initial filters saga

.github/workflows/preview.yml, DEV_CLIENT.md, app.config.ts, package.json, yarn.lock
=> Tr3v3r patch 2

src/core/transformators/objectDetails.ts
- Group included objects by category
<details>
<summary>Screenshots</summary>
</details>
=> Group included objects by category

src/screens/Filters/Filters.tsx
Clear filters state on close filter view
[EPMEDUGRN-861](https://jira.epam.com/jira/browse/EPMEDUGRN-861)
=> Сlear filters on close

src/components/atoms/Multiswitch/styles.ts, src/core/transformators/filters.ts, src/screens/Filters/Filters.tsx, src/screens/Filters/hooks/useFilters.tsx
=> fix(fixed): allow to check filters without any delay

src/api/graphql/queries/appMap.ts, src/api/graphql/queries/objectDetails.ts, src/api/graphql/queries/search.ts, src/components/atoms/Card/Card.tsx, src/components/atoms/ImageSlider/ImageSlider.tsx, src/components/atoms/SuspenseView/SuspenseView.tsx, src/components/atoms/SuspenseView/types.ts, src/core/selectors/search.ts, src/core/transformators/common.ts, src/core/transformators/objectDetails.ts, src/core/types/api/graphql.ts, src/core/types/common.ts, src/core/types/navigation.ts, src/screens/AppMap/hooks/useAppMap.tsx, src/screens/BookmarksList/hooks/useBookmarksList.tsx, src/screens/Home/hooks/useHome.tsx, src/screens/ObjectDetails/ObjectDetails.tsx, src/screens/ObjectDetails/hooks/useObjectDetails.tsx, src/screens/ObjectsList/hooks/useObjectsList.tsx, src/screens/Search/hooks/useSearch.tsx
add better transition for the object details page
=> add better transtion for object details page

src/components/atoms/HighlightedText/HighlightedText.tsx, src/components/atoms/HighlightedText/index.ts, src/components/atoms/HighlightedText/styles.ts, src/components/atoms/HighlightedText/utils.ts, src/components/atoms/index.ts, src/components/molecules/ListItem/BaseListItem.tsx, src/components/molecules/ListItem/types.ts, src/screens/Settlements/Settlements.tsx
Added HighlightedText component, that can return highlighted text by query or by span tags in the string.
=> fix(869): fix settlements text highlighting issue

src/core/transformators/filters.ts, src/core/types/navigation.ts, src/screens/Filters/Filters.tsx, src/screens/Filters/hooks/useFilters.tsx, src/screens/Settlements/Settlements.tsx, src/screens/Settlements/hooks/useSettlements.ts
add show case to disable regions if settlement selected
=> add show case to disable regions if settlement selected

App.tsx, README.md, babel.config.js, src/components/atoms/Preview/Preview.tsx, tsconfig.json
=> add preview function to isolate components for development

src/core/types/navigation.ts, src/navigation/navigators/HomeNavigator.tsx, src/navigation/navigators/MainNavigator.tsx, src/screens/Filters/types.ts, src/screens/Search/types.ts, src/screens/Settlements/types.ts
Extra TabBar for android on the filter screen
NA
<details>
https://github.com/user-attachments/assets/e9c13059-c1ac-47e7-a274-3e1321f383f0
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-874
NA
NA
=> fix(874): fix bug with TabBar for android on filter screen

src/components/molecules/ListItem/ListItem.tsx, src/components/molecules/ListItem/components/ListItemCheckbox/ListItemCheckbox.tsx, src/components/molecules/ListItem/components/ListItemPrimary/ListItemPrimary.tsx, src/components/molecules/ListItem/components/ListItemPrimary/index.ts, src/components/molecules/ListItem/components/ListItemPrimary/styles.ts, src/components/molecules/ListItem/components/ListItemSwitch/ListItemSwitch.tsx, src/components/molecules/ListItem/components/ListItemSwitch/index.ts, src/components/molecules/ListItem/components/ListItemSwitch/styles.ts, src/components/molecules/ListItem/components/index.ts, src/components/molecules/ListItem/index.ts, src/components/molecules/ListItem/styles.ts, src/components/molecules/ListItem/types.ts, src/components/molecules/ObjectShareExperienceMenu/ObjectShareExperienceMenu.tsx, src/components/organisms/ObjectDetailsListItemsMenu/ObjectDetailsListItemsMenu.tsx, src/screens/Filters/Filters.tsx, src/screens/Filters/styles.ts, src/screens/ObjectDetails/components/ObjectInfoSection/ObjectInfoSection.tsx, src/screens/ObjectDetailsAddInfo/ObjectDetailsAddInfo.tsx, src/screens/Settlements/Settlements.tsx
Makes ListItem component that wraps ListItemCheckbox, ListItemSwitch or ListItemPrimary
=> feat(699): Make ListItem wrapper component

src/api/graphql/queries/search.ts, src/components/atoms/HighlightedText/HighlightedText.tsx, src/components/atoms/HighlightedText/styles.ts, src/components/atoms/HighlightedText/utils.ts, src/components/molecules/ListItem/BaseListItem.tsx, src/components/molecules/ListItem/components/ListItemPrimary/ListItemPrimary.tsx, src/components/molecules/ListItem/types.ts, src/components/molecules/SearchListItem/SearchListItem.tsx, src/components/molecules/SearchListItem/styles.ts, src/core/actions/search.ts, src/core/reducers/search.ts, src/core/sagas/search/searchObjectsSaga.ts, src/core/selectors/search.ts, src/core/transformators/search.ts, src/core/types/api/graphql.ts, src/core/types/common.ts, src/screens/ObjectDetails/components/ObjectInfoSection/ObjectInfoSection.tsx, src/screens/Settlements/Settlements.tsx
1) Adds highlight for search list item.
2) Update BaseListItem
3) Update HighlightText component
=> search item highlight

App.tsx
fixed modals behavior on Android
=> fix(852): fixed modals behavior on Android

src/components/atoms/HighlightedText/HighlightedText.tsx, src/components/molecules/ListItem/BaseListItem.tsx, src/components/molecules/SearchField/SearchField.tsx, src/components/molecules/SearchField/styles.ts, src/core/selectors/settlements.ts, src/core/transformators/settlements.ts, src/screens/Settlements/Settlements.tsx, src/screens/Settlements/hooks/useSettlements.ts
Adjust filtering by settlements: place selected settlements on top
https://jira.epam.com/jira/browse/EPMEDUGRN-876
NA
NA
=> fix(876): place selected settlements on top

src/components/molecules/GeneralListItem/GeneralListItem.tsx, src/components/molecules/GeneralListItem/styles.ts, src/screens/ProfileDetails/hooks/useProfileDetails.tsx
1. Removed redundant text from the logout alert.
2. Fixed the loader position when logging out.
=> fix(878, 879): fix loader position and remove redunant logout text

src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/common.ts, src/api/graphql/queries/filters.ts, src/api/graphql/queries/search.ts, src/core/actions/filters.ts, src/core/actions/search.ts, src/core/constants.ts, src/core/hooks/useSearchList.ts, src/core/reducers/filters.ts, src/core/sagas/filters/filtersPage.ts, src/core/sagas/filters/getFiltersDataSaga.ts, src/core/sagas/filters/getInitialFiltersSaga.ts, src/core/sagas/search/searchObjectsSaga.ts, src/core/selectors/filtersPage.ts, src/core/selectors/search.ts, src/core/transformators/filters.ts, src/core/transformators/search.ts, src/core/types/api/graphql.ts, src/core/types/filters.ts, src/core/types/navigation.ts, src/screens/Filters/Filters.tsx, src/screens/Filters/hooks/useFilters.tsx, src/screens/Filters/types.ts, src/screens/Search/screenOptions.tsx, src/screens/Search/styles.ts
join filters and search functionalities
1) Update search and filters queries to have common input
2) Add bage to show applied filters on search
3) Pass needed data from Filter screen to Search and vice versa.
Open question - what to show on search when user clicks on Show button when no filters applied ( whole list or empty list ? )
=> feat(updated): join filters and search functionalities

src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/common.ts, src/api/graphql/queries/search.ts, src/core/actions/index.ts, src/core/actions/search.ts, src/core/actions/searchHistory.ts, src/core/hooks/useSearchList.ts, src/core/reducers/index.ts, src/core/reducers/search.ts, src/core/reducers/searchHistory.ts, src/core/sagas/search/getSearchObjectsHistorySaga.ts, src/core/sagas/search/search.ts, src/core/sagas/search/searchObjectsSaga.ts, src/core/selectors/index.ts, src/core/selectors/search.ts, src/core/selectors/searchHistory.ts, src/core/store.ts, src/core/types/api/graphql.ts, src/navigation/navigators/HomeNavigator.tsx, src/screens/Filters/styles.ts, src/screens/Home/screenOptions.tsx, src/screens/Home/styles.ts
Search improvements, UI bug fixes
Fixes https://jiraeu.epam.com/browse/EPMEDUGRN-916
=> fix(fixed): search improvements, UI bug fixes

src/components/organisms/SearchList/SearchList.tsx, src/core/actions/search.ts, src/core/hooks/useSearchList.ts, src/core/reducers/search.ts, src/core/sagas/search/searchObjectsSaga.ts, src/core/selectors/search.ts, src/core/transformators/appMap.ts, src/core/transformators/common.ts, src/core/transformators/search.ts, src/core/transformators/settlements.ts, src/core/types/bookmarksDetails.ts, src/core/types/common.ts, src/screens/AppMap/hooks/useAppMap.tsx, src/screens/Filters/hooks/useFilters.tsx, src/screens/Search/hooks/useSearch.tsx, src/screens/Search/screenOptions.tsx, src/screens/Settlements/hooks/useSettlements.ts
fixed types, start search only on 3rd symbol
=> fix(fixed): fixed types, start search only on 3rd symbol

src/locale/en.json
Correct "Hide visited" filter name
[EPMEDUGRN-932](https://jiraeu.epam.com/browse/EPMEDUGRN-932)
=> fix(932): correct "hide visited" filter name (en)

src/components/atoms/Chip/Chip.tsx, src/components/molecules/ObjectDetailsBottomButtons/ObjectDetailsBottomButtons.tsx, src/components/molecules/SearchField/SearchField.tsx, src/core/constants.ts, src/core/hooks/useSearchList.ts, src/core/selectors/searchHistory.ts, src/core/types/analytics/common.ts, src/core/types/analytics/filters.ts, src/core/types/analytics/index.ts, src/core/types/analytics/search.ts, src/core/types/api/graphql.ts, src/core/types/navigation.ts, src/screens/Filters/Filters.tsx, src/screens/Filters/hooks/index.tsx, src/screens/Filters/hooks/useFilters.tsx, src/screens/Filters/hooks/useFiltersAnalytics.ts, src/screens/Home/hooks/index.tsx, src/screens/Home/hooks/useHomeAnalytics.ts, src/screens/Home/screenOptions.tsx, src/screens/Search/hooks/useSearch.tsx, src/screens/Search/hooks/useSearchAnalytics.ts, src/screens/Search/screenOptions.tsx, src/screens/Settlements/Settlements.tsx, src/screens/Settlements/hooks/useSettlements.ts, src/screens/Settlements/hooks/useSettlementsAnalytics.ts
1) add analytics for search and filters
2) Fix bug with white screen on search history
3) Fix bug with icons on object details
=> Analyitcs and bug fixes

src/components/molecules/FilterDistance/FilterDistance.tsx, src/screens/Filters/Filters.tsx
show distance slider only if location exist
=> show distance slider only if location exist

src/core/reducers/searchHistory.ts
https://jiraeu.epam.com/browse/EPMEDUGRN-960
=> fix(fixed): (970)[https://jiraeu.epam.com/browse/EPMEDUGRN-970]

src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/search.ts, src/core/reducers/user.ts
=> fix search history

src/api/graphql/queries/search.ts
=> fix query for search hostory

src/components/molecules/SearchListItem/SearchListItem.tsx, src/core/types/analytics/search.ts, src/screens/Search/hooks/useSearchAnalytics.ts
fix analytics, fix search highlight
=> fix(fixed): fix analytics, fix search highlight

src/core/sagas/bookmarksDetails/getBookmarksInitialObjectsDataSaga.ts
Fixed bookmarks filter to fetch only published content
=> fix(976): fixed bookmarks filter

src/components/organisms/AuthForm/styles.ts, src/core/sagas/visitedObjects/sendEmailSaga.ts, src/screens/ObjectDetailsShareExperience/ObjectDetailsShareExperience.tsx
=> fix minor bugs

src/core/reducers/visitedObjects.ts, src/core/transformators/search.ts
Fixes
https://jiraeu.epam.com/browse/EPMEDUGRN-991
https://jiraeu.epam.com/browse/EPMEDUGRN-993
=> fix(fixed): fix issue with mark visited, add sorting for search results

src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/filters.ts, src/core/sagas/filters/getFiltersDataSaga.ts
add app locale to filters query
=> fix(fixed): add app locale to filters query

src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/homePage.ts, src/core/actions/home.ts, src/core/reducers/home.ts, src/core/sagas/homePage/fetchRandomObjects.ts, src/core/sagas/homePage/getHomePageDataSaga.ts, src/core/sagas/homePage/homePage.ts, src/core/selectors/homePage.ts, src/core/types/api/graphql.ts, src/core/types/utils/effectType.ts, src/core/types/utils/index.ts, src/screens/Home/Home.tsx, src/screens/Home/hooks/useOpenRandomObject.ts
=> feat(added): [1009] add random object functionality

src/components/atoms/Chip/Chip.tsx, src/components/atoms/Chip/constants.ts, src/components/atoms/Chip/index.ts, src/components/atoms/index.ts, src/components/molecules/ChipsHorisontalList/ChipsHorisontalList.tsx, src/components/molecules/ChipsHorisontalList/index.ts, src/components/molecules/ChipsHorisontalList/styles.ts, src/components/molecules/index.ts
Add ChipsHorisontalList
NA
https://github.com/user-attachments/assets/ce848e20-bc85-4d33-8985-e4e7dacc275f
https://jiraeu.epam.com/browse/EPMEDUGRN-1023
NA
=> [EPMEDUGRN-1023]: add ChipsHorisontalList

src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/homePage.ts, src/components/molecules/ObjectCardNew/ObjectCardNew.tsx, src/components/molecules/ObjectCardNew/styles.ts, src/core/actions/home.ts, src/core/reducers/home.ts, src/core/sagas/homePage/getHomePageDataSaga.ts, src/core/selectors/homePage.ts, src/core/transformators/common.ts, src/core/transformators/homePage.ts, src/core/types/api/graphql.ts, src/core/types/common.ts, src/screens/Home/Home.tsx, src/screens/Home/components/SpotOfTheWeekWidget/SpotOfTheWeekWidget.tsx, src/screens/Home/hooks/usePlaceOfTheWeek.ts
integrate place of the week API
https://jiraeu.epam.com/browse/EPMEDUGRN-1024
=> feat(added): integrate place of the week

app.config.ts, src/api/graphql/queries/common.ts, src/components/molecules/ChipsHorisontalList/ChipsHorisontalList.tsx, src/components/molecules/ChipsHorisontalList/styles.ts, src/core/actions/home.ts, src/core/hooks/analytics/useHomeAnalytics.ts, src/core/reducers/home.ts, src/core/sagas/homePage/getHomePageDataSaga.ts, src/core/selectors/homePage.ts, src/core/transformators/homePage.ts, src/core/types/api/graphql.ts, src/core/types/homePage.ts, src/screens/Home/Home.tsx, src/screens/Home/components/SpotOfTheWeekWidget/SpotOfTheWeekWidget.tsx, src/screens/Home/hooks/useHome.tsx
feat(added): update home page categories
=> feat(added): update home page categories

package.json, src/api/graphql/GraphQLAPI.ts, src/api/graphql/queries/bookmarksDetails.ts, src/api/graphql/queries/homePage.ts, src/core/actions/bookmarksDetails.ts, src/core/actions/objectsList.ts, src/core/reducers/bookmarksDetails.ts, src/core/sagas/bookmarksDetails/getBookmarksInitialObjectsDataSaga.ts, src/core/sagas/objectsList/getObjectsListDataSaga.ts, src/core/transformators/objectsList.ts, src/core/types/api/graphql.ts, src/core/types/navigation.ts, src/core/types/objectsList.ts, src/locale/en.json, src/locale/ru.json, src/screens/BookmarksList/hooks/useBookmarksList.tsx, src/screens/Home/Home.tsx, src/screens/Home/hooks/index.tsx, src/screens/Home/hooks/usePlacesYouWontFindWidget.ts, src/screens/ObjectsList/hooks/useObjectsList.tsx
=> feat(added): [EPMEDUGRN-1027] add places you won't find on google maps widget integration

src/components/organisms/ModalForm/ModalForm.tsx, src/components/organisms/ModalForm/components/FieldEditorSheet/FieldEditorSheet.tsx, src/components/organisms/ModalForm/types.ts, src/core/types/addNewPlace.ts, src/core/types/common.ts, src/screens/Home/components/AddLocationWidget/index.ts, src/screens/Home/components/AddNewPlaceWidget/AddNewPlaceWidget.tsx, src/screens/Home/components/AddNewPlaceWidget/index.ts, src/screens/Home/components/AddNewPlaceWidget/styles.ts, src/screens/Home/components/index.ts
=> fix(added): [EPMEDUGRN-1051] fix 'Add New Place' widget layout, improve UX

src/components/organisms/ModalForm/components/FieldSet/FieldSet.tsx, src/locale/en.json, src/locale/ru.json
=> fix(added): 'Add new place' widget UI fixes

src/core/selectors/app.ts
=> fix: disable update notification when current version matches the updated

src/components/organisms/MapWithBottomSheet/MapWithBottomSheet.tsx
https://jiraeu.epam.com/browse/EPMEDUGRN-1106
=> [EPMEDUGRN-1106] set accesible to false to allow inspect items inside
