- src/components/molecules/ObjectDescriptionSource/ObjectDescriptionSource.tsx
- src/components/molecules/ObjectDescriptionSource/index.ts
- src/components/molecules/ObjectDescriptionSource/styles.ts
- src/components/molecules/index.ts
- src/components/screens/ObjectDetails/ObjectDetails.tsx
- src/components/screens/ObjectsList/ObjectsList.tsx
- src/core/types/common.ts
- src/locale/ru.json
New separate field for sources-links (under description) was created. UI keeps the same view.
Ticket-253: https://github.com/radzima-green-travel/green-travel-combine/issues/253
> Refactor: add separate field for source-info at ObjectDetail-screen

- ios/screens/DetailsViewController/DetailsViewController.m
Showed the scrollbar when detail view is bounce vertically. 
Uploading 173575263-a73dbf44-d33e-4c97-acb3-c314767aaf13.mp4…
https://user-images.githubusercontent.com/66625413/173960587-e279b8cb-7236-46ad-a47e-14d5ad4221ae.mov
al._
https://github.com/radzima-green-travel/green-travel-combine/issues/423
> fix/423 Changed the layer hierarchy in DetailsViewController

- ios/greenTravel/Images.xcassets/Colors/bottomSheetGrip.colorset/Contents.json
- ios/greenTravel/Images.xcassets/Colors/textFieldBackground.colorset/Contents.json
- ios/greenTravel/Images.xcassets/Colors/textFieldBorderColor.colorset/Contents.json
- ios/utilities/Colors.h
- ios/utilities/Colors.m
- ios/views/CommonTextField/CommonTextField.m
- ios/views/SecureTextField/SecureTextField.m
added textfield border color and background color from Figma
#451 
> fix(451): add textfield background color for dark mode

- ios/screens/PlacesViewController/PlacesViewController.m
fix the application crashes when the user tries to remove an object from favorites.
fix when you add an item to favorites, it ends up on the wrong screen.
#392
#469 
https://user-images.githubusercontent.com/83513326/180202594-da203ea8-bb90-42c5-96de-83c002b2e413.mov
#392 
#469 
> fix(392): bookmarks not update after adding new item

- ios/screens/ProfileRootViewController/LoginViewController/CommonFormConstants.h
- ios/screens/ProfileRootViewController/LoginViewController/CommonFormConstants.m
- ios/screens/ProfileRootViewController/ResetPasswordEMailViewController/ResetPasswordEMailViewController.m
Adds bottom constraint to button.
https://user-images.githubusercontent.com/7137128/180479321-fea9b96e-8fa6-43ac-b3f8-7ca4dd938a51.mov
https://user-images.githubusercontent.com/7137128/180479579-d9b90e6d-009e-4950-87c0-9601933f69eb.mov
#464 
> fix(464): no bottom constraint for button

- ios/greenTravel.xcodeproj/project.pbxproj
- ios/greenTravel/greenTravelDebug.entitlements
Added two domain associations ([documentation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_associated-domains?language=objc)):
```
webcredentials:d1u39lnww2smbf.cloudfront.net
webcredentials:radzima.app
```
[EPMEDUTOUR-10303](https://jira.epam.com/jira/browse/EPMEDUTOUR-10303)
> fix(EPMEDUTOUR-10303): add webcredentials domain association

- ios/screens/ProfileRootViewController/ResetPasswordNewPasswordViewController/ResetPasswordNewPasswordViewController.m
Lets new password screen to be scrolled in landscape mode.
#464 
> fix(464): new password screen can be scrolled

- ios/AppDelegate.m
- ios/screens/MapViewController/FullMapViewController.m
Sets color of status bar using deprecated API.
`[UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleLightContent;`
See [this discussion](https://github.com/radzima-green-travel/green-travel-combine/pull/398#discussion_r939527992) as to why deprecated API is used instead of view controller based status bar style.
#410 
https://github.com/radzima-green-travel/green-travel-combine/pull/398
> fix: color of status bar

- ios/screens/DetailsViewController/DetailsViewController.m
Fixes color of status bar on SFSafariViewController.
#410 
> fix(410): color of status bar of SFSafariViewController

- ios/screens/DetailsViewController/DetailsViewController.m
Fixes dark status bar style when popping DetailsViewController.
https://user-images.githubusercontent.com/7137128/185930370-8a88b35c-1728-423b-be62-877e1e2128b3.mp4
https://user-images.githubusercontent.com/7137128/185930328-03f7bb1e-7fe0-4c3b-a397-46ef30316a3a.mp4
#410 
> fix(410): color of status when popping DetailsViewController

- ios/screens/IndexViewController/PlacesTableViewCell/PlacesTableViewCell.m
Center "all" button with the gap between cells
If "all" has long text, align text to the right of screen with distance between right edge of text and right edge of screen = 16pt
https://github.com/radzima-green-travel/green-travel-combine/issues/561
> fix(561):  сenter all button with the gap between cells

- ios/screens/IndexViewController/PlacesTableViewCell/PhotoCollectionViewCell/PhotoCollectionViewCell.h
- ios/screens/IndexViewController/PlacesTableViewCell/PhotoCollectionViewCell/PhotoCollectionViewCell.m
Adds cache for images for bookmark selected states.
See #580 .
https://user-images.githubusercontent.com/7137128/190693232-f4e90bd5-9c10-4e1b-bd62-0deed28e75e2.mov
https://user-images.githubusercontent.com/7137128/190693261-e2e74369-6071-473b-8ff9-e75a5f334d52.mov
#580 
> fix(580): cache images for selected bookmarks

- ios/controllers/UserController/UserController.m
Fixes #606 , #607 . Fetches actual email after sign in within reset password flow.
#606, #607.
> fix(606): empty email after password reset. Fixes #607

- ios/greenTravel/Info.plist
Adds Info.plist key to make compliance check easier.
https://developer.apple.com/documentation/bundleresources/information_property_list/itsappusesnonexemptencryption?language=objc
#660 
> feat(660): add ITSAppUsesNonExemptEncryption=false

- ios/views/SecureTextField/SecureTextField.m
> fix(649) wrong image on hide/show password

- ios/greenTravel.xcodeproj/project.pbxproj
- explicitly add MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS in build settings
0 CoreData warnings
> feat(644): silence core data warnings

- ios/screens/DetailsViewController/DetailsViewController.m
- ios/screens/MapViewController/BaseMapViewController.m
- ios/screens/ProfileRootViewController/LoginViewController/BaseFormViewController.m
Fix missued UIKit methods and remove console log warning
Radzima Dev[32474:11577474] [ViewController] Calling -viewWillDisappear: directly on a view controller is not supported, and may result in out-of-order callbacks and other inconsistent behavior. Use the -beginAppearanceTransition:animated: and -endAppearanceTransition APIs on UIViewController to manually drive appearance callbacks instead. Make a symbolic breakpoint at UIViewControllerAlertForAppearanceCallbackMisuse to catch this in the debugger. View controller: <DetailsViewController: 0x11086e000>
> fix(uikit): fix missused uikit methods

- src/screens/NewPassword/hooks/useNewPassword.tsx
Disable button for invalid password
[489](https://jira.epam.com/jira/browse/EPMEDUGRN-489)
> [489] disable button for invalid password

- ios/Podfile.lock
- package.json
- yarn.lock
Updated 'expo-image' library.
https://github.com/radzima-green-travel/green-travel-combine/assets/82803292/f99727c8-417b-403e-a46f-30138741b8b4
[490](https://jira.epam.com/jira/browse/EPMEDUGRN-490)
> fix(490): photos visibility after app reload

- src/screens/NewPassword/hooks/useNewPassword.tsx
Fix disabling save button when the password field is empty.
[489](https://jira.epam.com/jira/browse/EPMEDUGRN-489)
> fix(489): save button state

- src/components/molecules/DetailsPageCapture/DetailsPageCapture.tsx
- src/locale/en.json
- src/locale/ru.json
Add translation for copy location text
[614](https://jira.epam.com/jira/browse/EPMEDUGRN-614).
> fix(fixed): [614] translation for copy location

- src/components/atoms/FormInput/FormInput.tsx
- src/components/atoms/FormInput/styles.ts
Modify `FormInput` component for multiline text input
<details>
</details>
> feat(added): [638] multiline text input

- src/components/molecules/ListItem/BaseListItem.tsx
- src/components/molecules/ListItem/ListItem.tsx
- src/components/molecules/ListItem/ListItemWrapper.tsx
- src/components/molecules/ListItem/index.ts
- src/components/molecules/ListItem/styles.ts
- src/components/molecules/ListItem/types.ts
- src/components/molecules/index.ts
Added list item component
<details>
</details>
> feat(added): [567] list item component

- src/core/selectors/app.ts
In this PR, mandatory update has been disabled for DEV
<details>
</details>
<details>
</details>
NA
NA
NA
> feat(0000): make update optional for dev

- src/screens/ObjectDetailsAddInfo/ObjectDetailsAddInfo.tsx
- src/screens/ObjectDetailsAddInfo/hooks/useObjectDetailsAddInfo.ts
Fix ObjectDetailsAddInfo issue when entered information gets lost if users click Back on Suggest new info screen by adding a new modal window
<Details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/b519adc1-aeb1-42a6-b30c-cccc7e37ce5a
</Details>
<Details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/654f6d62-9508-4166-a987-7ffbda614753
</Details>
https://jira.epam.com/jira/browse/EPMEDUGRN-728
NA
NA
> feat(728): disable screen touchability when loading is true

- src/components/molecules/ObjectAddInfoMenu/ObjectAddInfoMenu.tsx
Add disable for submit button for ObjectAddInfoMenu
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/616a54c5-62db-4ecb-a139-15949ae6b396
</details>
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/d6192bb0-7ff6-4401-b298-a1ca7564ea0e
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-740
> feat(740): add disable for submit button for ObjectAddInfoMenu

- src/locale/en.json
Update translations for dinerPlaces
<details>
</details>
<details>
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-750
NA
NA
> fix(750): update translations for dinerPlaces

- src/screens/ObjectDetails/hooks/useObjectDetailsInfo.ts
'Phone number' located under 'Official website' field instead 'Average visit time' field.
<details>
</details>
<details>
</details>
https://plus.epam.com/task/26021
NA
NA
> fix(0000): update position for phone number

- src/components/organisms/HomeSectionBar/HomeSectionBar.tsx
- src/components/organisms/HomeSectionBar/styles.ts
Part of the previous card is invisible while scrolling
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/d0a54a03-0353-42f6-be99-c36b480a22e8
</details>
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/3e77fa65-5bb4-4f9d-bc11-02f340976196
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-748
NA
NA
> fix(748): part of the previous card is invisible while scrolling

- src/components/molecules/ObjectAddInfoMenu/ObjectAddInfoMenu.tsx
This PR makes the 'Done' button clickable if after was initially filled in after removing the value
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/f7efec2c-3197-4485-86d5-5ff67e6872e6
</details>
<details>
https://github.com/radzima-green-travel/green-travel-combine/assets/68128028/33baaf6e-8ed3-429f-957b-c5627ed4038b
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-742
NA
NA
> fix(742): fix field order mismatch by design

- src/components/atoms/Multiswitch/styles.ts
Fix Google rating filter by updating ratings items layout, so now each item has the same size
https://jira.epam.com/jira/browse/EPMEDUGRN-860
> fix(860): make the Google rating filter fit the screen

- src/core/transformators/settlements.ts
Fix for the settlements list is not displayed in alphabetic order in EN
<details>
</details>
<details>
https://github.com/user-attachments/assets/77887ff6-c315-48d1-826d-1b6e69a626bd
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-868
NA
NA
> fix(868): fix bug with settlements list is not displayed in alphabetic order

- src/screens/Settlements/Settlements.tsx
Hide apply button after opening keyboard on settlements screen
NA
<details>
https://github.com/user-attachments/assets/3bff8afe-2aa0-4e63-a05a-1f3550a6d231
</details>
https://jira.epam.com/jira/browse/EPMEDUGRN-874
NA
NA
> fix(874): hide apply button after opening keyboard on settlements screen

- src/components/molecules/FiltersSectionContainer/styles.ts
Fix bug with 'Settlements' option in Filters is displayed not in bold as designed
<details>
</details>
<details>
</details>
https://jiraeu.epam.com/browse/EPMEDUGRN-917
NA
> Fix/917 'Settlements' option in Filters is displayed not in bold as designed

- src/screens/Settlements/Settlements.tsx
Fix bug with the empty space under the Search bar appears when a user unselects chosen options
<details>
https://github.com/user-attachments/assets/4990f269-9df7-4601-af21-c30602eddc0a
</details>
<details>
https://github.com/user-attachments/assets/8206dc3b-28d0-41f0-b1d8-6b0e029df59a
</details>
https://jiraeu.epam.com/browse/EPMEDUGRN-915
NA
> Fix/915 The empty space under the Search bar appears when a user unselects chosen options

- app.json
- eas.json
1. Changed distribution from internal to store for the prod build;
2. Added usesNonExemptEncryption false into iOS config to avoid adding encryption type each type the build is deployed. Since we don't use custom encryption, we must set it to false.
> fix(906): fix configuration for expo prod build

- app.config.ts
- config-plugins/withAndroidQueries.js
As per [expo documentation](https://docs.expo.dev/linking/into-other-apps/#specify-android-intents-to-handle-common-url), for Android 11 (API level 30) and above we have to specify the intents your app will handle in the AndroidManifest.xml file.
Added a custom plugin according to the docs. It fixes the navigation issue for mailto and tel links.
> fix(939): added custom plugin to fix mailto and tel links for Android

- src/core/transformators/filters.ts
Update checkIfFiltersAreUnset trabformator
[EPMEDUGRN-934](https://jiraeu.epam.com/browse/EPMEDUGRN-934)
> fix(934): clear filter button is enabled when only hide visited filter is on

- src/components/molecules/FilterDistance/FilterDistance.tsx
[[EPMEDUGRN-951] The 'Consider the distance' km value returns to default number when a user comes back to the filters from results screen](https://jiraeu.epam.com/browse/EPMEDUGRN-951)
> fix(923): fix bug with returning distance filter value to default value
